stages:
  - test
  - deploy

cache:
  paths:
    - vendor/
    - node_modules/

test:
  stage: test
  image: composer
  script:
    - cp .env.example .env
    - composer install
    - sh cs_check
    - php artisan key:generate

production:
  stage: deploy
  image: composer
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  script:
    - ssh -o StrictHostKeyChecking=no $USER@$HOST 'cd /var/www/vhosts/phphints.com/crud.phphints.com;git init;git pull;/opt/plesk/php/8.0/bin/php /var/www/vhosts/phphints.com/composer.phar update;/opt/plesk/php/8.0/bin/php artisan migrate;npm i;npm run production'
  only:
    - master    
