stages:
  - test
  - deploy

cache:
  paths:
    - vendor/
    - node_modules/

test:
  stage: test
  image: composer
  script:
    - cp .env.example .env
    - composer install
    - sh cs_check
    - php artisan key:generate

production:
  stage: deploy
  script:
    - ssh $USER@$HOST 'cd /var/www/vhosts/phphints.com/crud.phphints.com'
  only:
    - master
